/* ============================================================
   M&A Hub — Pipeline + IC Scorecards from Monday.com
   Data source: window.MONDAY (generated by generate_monday_dashboard.py)
   ============================================================ */
(function () {
    'use strict';

    var DEAD_GROUPS = ['Dead', 'Unsuccessful Offers', 'Templates'];
    var STAGE_ORDER = [
        'Prospective Deals', 'Introd to CDD', 'IMs/Data Packs',
        'In Progress Deals', 'Completed'
    ];
    var STAGE_COLORS = ['#334FB4', '#a78bfa', '#3CB4AD', '#f59e0b', '#34d399'];
    var PALETTE = window.PALETTE || ['#3CB4AD', '#334FB4', '#a78bfa', '#34d399', '#f472b6', '#f59e0b'];

    function esc(s) { var d = document.createElement('div'); d.textContent = s || ''; return d.innerHTML; }
    function fmtK(v) {
        if (!v) return '£0';
        if (v >= 1000000) return '£' + (v / 1000000).toFixed(1) + 'M';
        if (v >= 1000) return '£' + (v / 1000).toFixed(0) + 'K';
        return '£' + Number(v).toLocaleString('en-GB');
    }
    function relDate(iso) {
        if (!iso) return '';
        var d = new Date(iso);
        var diff = Math.floor((Date.now() - d.getTime()) / 86400000);
        if (diff === 0) return 'Today';
        if (diff === 1) return 'Yesterday';
        if (diff < 7) return diff + 'd ago';
        if (diff < 30) return Math.floor(diff / 7) + 'w ago';
        return Math.floor(diff / 30) + 'mo ago';
    }

    // ── Tab switching ──
    window.switchMATab = function (tabKey) {
        var tabs = document.getElementById('ma-hub-tabs');
        if (tabs) {
            tabs.querySelectorAll('.ma-hub-tab').forEach(function (btn) {
                btn.classList.toggle('active', btn.getAttribute('data-matab') === tabKey);
            });
        }
        document.querySelectorAll('.ma-hub-panel').forEach(function (p) { p.classList.remove('active'); });
        var panel = document.getElementById('ma-panel-' + tabKey);
        if (panel) panel.classList.add('active');
    };

    // ================================================================
    // Pipeline Tab
    // ================================================================
    function renderPipelineKPIs(projects) {
        var el = document.getElementById('ma-kpi-totals');
        if (!el) return;

        var active = projects.filter(function (p) { return DEAD_GROUPS.indexOf(p.group) === -1; });
        var inProgress = active.filter(function (p) {
            return p.group === 'In Progress Deals' || p.group === 'IMs/Data Packs';
        });
        var prospective = active.filter(function (p) {
            return p.group === 'Prospective Deals' || p.group === 'Introd to CDD';
        });
        var completed = projects.filter(function (p) { return p.group === 'Completed'; });
        var totalValue = projects.reduce(function (s, p) { return s + (p.value || 0); }, 0);

        var cards = [
            { label: 'Active Deals', value: active.length, color: '#3CB4AD' },
            { label: 'In Progress', value: inProgress.length, color: '#f59e0b' },
            { label: 'Prospective', value: prospective.length, color: '#334FB4' },
            { label: 'Completed', value: completed.length, color: '#34d399' },
            { label: 'Pipeline Value', value: fmtK(totalValue), color: '#a78bfa' }
        ];

        var html = '';
        cards.forEach(function (c) {
            html += '<div class="pl-act-card">'
                + '<div class="pl-act-label">' + c.label + '</div>'
                + '<div class="pl-act-value" style="color:' + c.color + '">' + c.value + '</div>'
                + '</div>';
        });
        el.innerHTML = html;
    }

    function renderFunnel(projects) {
        var el = document.getElementById('ma-funnel');
        if (!el) return;

        var counts = {};
        STAGE_ORDER.forEach(function (s) { counts[s] = 0; });
        projects.forEach(function (p) {
            if (counts.hasOwnProperty(p.group)) counts[p.group]++;
        });

        var maxVal = Math.max.apply(null, STAGE_ORDER.map(function (s) { return counts[s]; })) || 1;
        var html = '';
        STAGE_ORDER.forEach(function (stage, i) {
            var count = counts[stage];
            var pct = Math.max(3, (count / maxVal) * 100);
            html += '<div class="stat-bar-item">'
                + '<div class="stat-bar-header">'
                + '<span class="stat-bar-label">' + stage + '</span>'
                + '<span class="stat-bar-value">' + count + '</span></div>'
                + '<div class="stat-bar-track">'
                + '<div class="stat-bar-fill" style="width:' + pct.toFixed(1) + '%;background:' + STAGE_COLORS[i]
                + '"></div></div></div>';
        });
        el.innerHTML = html || '<div class="pl-empty">No deal flow data</div>';
    }

    function renderStatusBars(projects) {
        var el = document.getElementById('ma-status-bars');
        if (!el) return;

        var statuses = {};
        projects.forEach(function (p) {
            if (DEAD_GROUPS.indexOf(p.group) !== -1) return;
            var s = p.status || 'Unknown';
            statuses[s] = (statuses[s] || 0) + 1;
        });

        var sorted = Object.entries(statuses).sort(function (a, b) { return b[1] - a[1]; });
        var maxVal = sorted.length ? sorted[0][1] : 1;
        var html = '';
        sorted.forEach(function (entry, i) {
            var pct = Math.max(3, (entry[1] / maxVal) * 100);
            html += '<div class="stat-bar-item">'
                + '<div class="stat-bar-header">'
                + '<span class="stat-bar-label">' + esc(entry[0]) + '</span>'
                + '<span class="stat-bar-value">' + entry[1] + '</span></div>'
                + '<div class="stat-bar-track">'
                + '<div class="stat-bar-fill" style="width:' + pct.toFixed(1) + '%;background:'
                + PALETTE[i % PALETTE.length] + '"></div></div></div>';
        });
        el.innerHTML = html || '<div class="pl-empty">No status data</div>';
    }

    function renderDealsTable(projects) {
        var el = document.getElementById('ma-deals-table');
        if (!el) return;

        var active = projects
            .filter(function (p) { return DEAD_GROUPS.indexOf(p.group) === -1; })
            .sort(function (a, b) { return (b.updated_at || '').localeCompare(a.updated_at || ''); });

        if (!active.length) {
            el.innerHTML = '<div class="pl-empty">No active deals</div>';
            return;
        }

        // Build IC score lookup
        var icLookup = {};
        var icItems = (window.MONDAY && window.MONDAY.ic_items) || [];
        icItems.forEach(function (item) {
            if (item.total_score > 0) icLookup[item.id] = item.total_score;
        });

        var html = '<table class="pl-deals-table"><thead><tr>'
            + '<th>Deal</th><th>Stage</th><th>Status</th>'
            + '<th>Owner</th><th>IC Score</th><th>CDD</th><th>Updated</th>'
            + '</tr></thead><tbody>';

        active.forEach(function (p) {
            var score = icLookup[p.id] || '';
            var subs = p.subitems_count > 0
                ? p.subitems_complete + '/' + p.subitems_count
                : '-';
            var scoreClass = score >= 200 ? 'color:#34d399' : score >= 100 ? 'color:#f59e0b' : '';

            html += '<tr>'
                + '<td class="pl-deal-name">' + esc(p.name) + '</td>'
                + '<td class="text-muted-sm">' + esc(p.group) + '</td>'
                + '<td><span class="pl-chip" style="font-size:11px">' + esc(p.status) + '</span></td>'
                + '<td>' + esc(p.owner || 'Unassigned') + '</td>'
                + '<td style="font-weight:700;' + scoreClass + '">' + (score || '-') + '</td>'
                + '<td>' + subs + '</td>'
                + '<td class="text-muted-sm">' + relDate(p.updated_at) + '</td>'
                + '</tr>';
        });

        html += '</tbody></table>';
        el.innerHTML = html;
    }

    // ================================================================
    // IC Scorecards Tab
    // ================================================================
    function renderICKPIs(icItems) {
        var el = document.getElementById('ma-ic-kpis');
        if (!el) return;

        var scored = icItems.filter(function (i) { return i.total_score > 0; });
        var totalScored = scored.length;
        var avgScore = totalScored > 0
            ? scored.reduce(function (s, i) { return s + i.total_score; }, 0) / totalScored
            : 0;
        var topItem = scored.sort(function (a, b) { return b.total_score - a.total_score; })[0];

        var cards = [
            { label: 'Scored Items', value: totalScored },
            { label: 'Average Score', value: avgScore.toFixed(0) },
            { label: 'Highest Score', value: topItem ? topItem.total_score : 0, sub: topItem ? topItem.name : '' }
        ];

        var html = '';
        cards.forEach(function (c) {
            html += '<div class="pl-act-card">'
                + '<div class="pl-act-label">' + c.label + '</div>'
                + '<div class="pl-act-value">' + c.value + '</div>'
                + (c.sub ? '<span class="text-muted-sm">' + esc(c.sub) + '</span>' : '')
                + '</div>';
        });
        el.innerHTML = html;
    }

    function renderICTable(icItems) {
        var el = document.getElementById('ma-ic-table');
        if (!el) return;

        var scored = icItems
            .filter(function (i) { return i.total_score > 0; })
            .sort(function (a, b) { return b.total_score - a.total_score; });

        if (!scored.length) {
            el.innerHTML = '<div class="pl-empty">No scored items</div>';
            return;
        }

        var html = '<table class="pl-deals-table"><thead><tr>'
            + '<th>#</th><th>Deal</th><th>Score</th>'
            + '<th>Type</th><th>Source</th><th>Status</th>'
            + '</tr></thead><tbody>';

        scored.forEach(function (item, i) {
            var cols = item.columns || {};
            var scoreColor = item.total_score >= 200 ? '#34d399'
                : item.total_score >= 100 ? '#f59e0b' : 'var(--text)';
            html += '<tr>'
                + '<td class="text-muted-sm">' + (i + 1) + '</td>'
                + '<td class="pl-deal-name">' + esc(item.name) + '</td>'
                + '<td style="font-weight:800;color:' + scoreColor + '">' + item.total_score + '</td>'
                + '<td class="text-muted-sm">' + esc(cols['Deal Type'] || '-') + '</td>'
                + '<td class="text-muted-sm">' + esc(cols['Deal Source'] || '-') + '</td>'
                + '<td><span class="pl-chip" style="font-size:11px">' + esc(item.status || '-') + '</span></td>'
                + '</tr>';
        });

        html += '</tbody></table>';
        el.innerHTML = html;
    }

    function renderICDistribution(icItems) {
        var el = document.getElementById('ma-ic-dist');
        if (!el) return;

        var buckets = [
            { label: '300+', min: 300, max: Infinity, count: 0 },
            { label: '200-300', min: 200, max: 300, count: 0 },
            { label: '100-200', min: 100, max: 200, count: 0 },
            { label: '50-100', min: 50, max: 100, count: 0 },
            { label: '1-50', min: 1, max: 50, count: 0 }
        ];

        icItems.forEach(function (item) {
            var s = item.total_score || 0;
            for (var i = 0; i < buckets.length; i++) {
                if (s >= buckets[i].min && s < buckets[i].max) {
                    buckets[i].count++;
                    break;
                }
            }
        });

        var maxVal = Math.max.apply(null, buckets.map(function (b) { return b.count; })) || 1;
        var colors = ['#34d399', '#3CB4AD', '#334FB4', '#a78bfa', '#f472b6'];
        var html = '';
        buckets.forEach(function (b, i) {
            var pct = Math.max(3, (b.count / maxVal) * 100);
            html += '<div class="stat-bar-item">'
                + '<div class="stat-bar-header">'
                + '<span class="stat-bar-label">' + b.label + '</span>'
                + '<span class="stat-bar-value">' + b.count + ' deals</span></div>'
                + '<div class="stat-bar-track">'
                + '<div class="stat-bar-fill" style="width:' + pct.toFixed(1) + '%;background:'
                + colors[i] + '"></div></div></div>';
        });
        el.innerHTML = html;
    }

    // ================================================================
    // Master render
    // ================================================================
    window.renderMAHub = function () {
        var data = window.MONDAY;
        if (!data || !data.projects) {
            // Show empty state if no Monday data
            var el = document.getElementById('ma-kpi-totals');
            if (el) el.innerHTML = '<div class="pl-empty">No Monday.com data loaded. Run generate_monday_dashboard.py to sync.</div>';
            return;
        }

        // Pipeline tab
        renderPipelineKPIs(data.projects);
        renderFunnel(data.projects);
        renderStatusBars(data.projects);
        renderDealsTable(data.projects);

        // IC tab
        renderICKPIs(data.ic_items || []);
        renderICTable(data.ic_items || []);
        renderICDistribution(data.ic_items || []);
    };
})();
