/* ============================================================
   M&A Hub — Main Table + Deal Flow + IC Scorecards
   Data source: window.MONDAY (generated by generate_monday_dashboard.py)
   ============================================================ */
(function () {
    'use strict';

    var DEAD_GROUPS = ['Dead', 'Unsuccessful Offers', 'Templates'];
    var STAGE_ORDER = [
        'Prospective Deals', 'Introd to CDD', 'IMs/Data Packs',
        'In Progress Deals', 'Completed'
    ];
    var STAGE_COLORS = {
        'Prospective Deals': '#334FB4',
        'Introd to CDD': '#a78bfa',
        'IMs/Data Packs': '#3CB4AD',
        'In Progress Deals': '#f59e0b',
        'Completed': '#34d399'
    };
    var STATUS_COLORS = {
        'Gate 0': '#334FB4', 'Gate 1': '#334FB4', 'Gate 2': '#334FB4', 'Gate 3': '#334FB4',
        'IM Received': '#1e293b', 'Pending Info': '#f59e0b', 'Pending scorecard': '#f59e0b',
        'Pending NDA': '#f59e0b', 'New Biz Opportunity': '#ec4899',
        'Disqualified IM': '#7c3aed', 'LOI Offer': '#ef4444',
        'Offer Retracted': '#ef4444', 'Unsuccessful Offer': '#ef4444',
        'Failed Process': '#ef4444', 'Completed': '#34d399',
        'Partial Data': '#6b7280'
    };
    var PRIORITY_COLORS = {
        '1 - High': '#ef4444', '2 - Medium': '#f59e0b',
        '3 - Low': '#3CB4AD', '4 - Unassigned': '#6b7280'
    };

    function esc(s) { var d = document.createElement('div'); d.textContent = s || ''; return d.innerHTML; }
    function fmtK(v) {
        if (!v) return '\u00a30';
        v = Number(v);
        if (v >= 1e6) return '\u00a3' + (v / 1e6).toFixed(1) + 'M';
        if (v >= 1e3) return '\u00a3' + (v / 1e3).toFixed(0) + 'K';
        return '\u00a3' + v.toLocaleString('en-GB');
    }
    function relDate(iso) {
        if (!iso) return '';
        var diff = Math.floor((Date.now() - new Date(iso).getTime()) / 86400000);
        if (diff === 0) return 'Today';
        if (diff === 1) return 'Yesterday';
        if (diff < 7) return diff + 'd ago';
        if (diff < 30) return Math.floor(diff / 7) + 'w ago';
        return Math.floor(diff / 30) + 'mo ago';
    }

    function chip(text, color) {
        if (!text || text === '-') return '<span class="text-muted-sm">-</span>';
        var bg = color || STATUS_COLORS[text] || '#6b7280';
        return '<span class="pl-chip" style="font-size:11px;background:' + bg + '20;color:' + bg
            + ';border:1px solid ' + bg + '40">' + esc(text) + '</span>';
    }

    function scoreCell(val, label) {
        if (!val || val === '0' || val === 0) return '<td class="text-muted-sm">-</td>';
        var n = Number(val);
        var c = n >= 70 ? '#34d399' : n >= 50 ? '#f59e0b' : '#ef4444';
        return '<td style="font-weight:700;color:' + c + '" title="' + esc(label || '') + '">' + n + '</td>';
    }

    // ── Tab switching ──
    window.switchMATab = function (tabKey) {
        var tabs = document.getElementById('ma-hub-tabs');
        if (tabs) {
            tabs.querySelectorAll('.ma-hub-tab').forEach(function (btn) {
                btn.classList.toggle('active', btn.getAttribute('data-matab') === tabKey);
            });
        }
        document.querySelectorAll('.ma-hub-panel').forEach(function (p) { p.classList.remove('active'); });
        var panel = document.getElementById('ma-panel-' + tabKey);
        if (panel) panel.classList.add('active');
    };

    // ================================================================
    // TAB 1: Main Table (grouped by stage)
    // ================================================================
    function renderMainTable(projects) {
        var el = document.getElementById('ma-main-table');
        if (!el) return;

        var groups = {};
        STAGE_ORDER.forEach(function (s) { groups[s] = []; });
        projects.forEach(function (p) {
            if (DEAD_GROUPS.indexOf(p.group) === -1 && groups[p.group]) {
                groups[p.group].push(p);
            }
        });

        var html = '';
        STAGE_ORDER.forEach(function (stage) {
            var items = groups[stage];
            if (!items || !items.length) return;
            var sc = STAGE_COLORS[stage] || '#6b7280';

            html += '<div style="margin-bottom:20px">'
                + '<div style="display:flex;align-items:center;gap:8px;padding:10px 12px;background:'
                + sc + '18;border-left:3px solid ' + sc + ';border-radius:6px;margin-bottom:8px">'
                + '<span style="font-weight:700;color:' + sc + '">' + esc(stage) + '</span>'
                + '<span class="pl-chip" style="font-size:11px;background:' + sc + '30;color:' + sc + '">'
                + items.length + ' deals</span></div>';

            html += '<div style="overflow-x:auto"><table class="pl-deals-table"><thead><tr>'
                + '<th>Deal</th><th>POC</th><th>Status</th><th>Priority</th>'
                + '<th>Deal Type</th><th>Deal Source</th><th>Valuation</th>'
                + '<th>Target %</th><th>IC Score</th><th>CDD</th><th>Updated</th>'
                + '</tr></thead><tbody>';

            items.sort(function (a, b) { return (b.updated_at || '').localeCompare(a.updated_at || ''); });

            items.forEach(function (p) {
                var cols = p.columns || {};
                var val = cols['Valuation'] ? fmtK(cols['Valuation']) : (p.value ? fmtK(p.value) : '-');
                var eq = cols['Target Equity Purchase'] ? cols['Target Equity Purchase'] + '%' : '-';
                var ic = cols['Latest IC Score (Avg.)'] || '';
                var icC = ic ? (Number(ic) >= 70 ? '#34d399' : Number(ic) >= 50 ? '#f59e0b' : '#ef4444') : '';
                var subs = p.subitems_count > 0 ? p.subitems_complete + '/' + p.subitems_count : '-';

                html += '<tr>'
                    + '<td class="pl-deal-name">' + esc(p.name) + '</td>'
                    + '<td class="text-muted-sm">' + esc(cols['POC'] || '-') + '</td>'
                    + '<td>' + chip(p.status) + '</td>'
                    + '<td>' + chip(cols['Priority'] || '-', PRIORITY_COLORS[cols['Priority']]) + '</td>'
                    + '<td class="text-muted-sm">' + esc(cols['Deal Type'] || '-') + '</td>'
                    + '<td class="text-muted-sm">' + esc(cols['Deal Source'] || '-') + '</td>'
                    + '<td style="font-weight:600">' + val + '</td>'
                    + '<td>' + esc(eq) + '</td>'
                    + '<td style="font-weight:700;' + (icC ? 'color:' + icC : '') + '">' + (ic || '-') + '</td>'
                    + '<td class="text-muted-sm">' + subs + '</td>'
                    + '<td class="text-muted-sm">' + relDate(p.updated_at) + '</td>'
                    + '</tr>';
            });

            // Summary row
            var totalVal = items.reduce(function (s, p) {
                return s + Number((p.columns || {})['Valuation'] || p.value || 0);
            }, 0);
            var scoredItems = items.filter(function (p) { return (p.columns || {})['Latest IC Score (Avg.)']; });
            var avgIC = scoredItems.length
                ? (scoredItems.reduce(function (s, p) { return s + Number(p.columns['Latest IC Score (Avg.)']); }, 0) / scoredItems.length).toFixed(0)
                : '-';

            html += '<tr style="background:var(--card-bg);font-weight:600;border-top:2px solid var(--card-border)">'
                + '<td colspan="6" style="text-align:right;color:var(--text-muted)">Group Total</td>'
                + '<td>' + (totalVal > 0 ? fmtK(totalVal) : '-') + '</td>'
                + '<td></td><td>' + avgIC + '</td><td colspan="2"></td></tr>';

            html += '</tbody></table></div></div>';
        });

        el.innerHTML = html || '<div class="pl-empty">No active deals</div>';
    }

    // ================================================================
    // TAB 2: Deal Flow Performance
    // ================================================================
    function renderPerfKPIs(projects) {
        var el = document.getElementById('ma-perf-kpis');
        if (!el) return;

        var ims = projects.filter(function (p) {
            return p.status === 'IM Received' || p.group === 'IMs/Data Packs';
        });
        var gate0 = projects.filter(function (p) {
            return p.status === 'Gate 0' || (p.columns || {})['Gate 0 Approval'] === 'v';
        });
        var offers = projects.filter(function (p) {
            return p.status === 'LOI Offer' || p.status === 'Offer Retracted' || p.status === 'Unsuccessful Offer';
        });
        var disqualified = projects.filter(function (p) {
            return p.status === 'Disqualified IM' || p.status === 'Failed Process';
        });
        var completed = projects.filter(function (p) {
            return p.status === 'Completed' || p.group === 'Completed';
        });

        var cards = [
            { label: 'Total Opportunities', value: projects.length, color: '#334FB4' },
            { label: 'Total IMs', value: ims.length, color: '#3CB4AD' },
            { label: 'Gate 0', value: gate0.length, color: '#a78bfa' },
            { label: 'Offers', value: offers.length, color: '#f59e0b' },
            { label: 'Disqualified', value: disqualified.length, color: '#ef4444' },
            { label: 'Successful', value: completed.length, color: '#34d399' }
        ];

        var html = '';
        cards.forEach(function (c) {
            html += '<div class="pl-act-card">'
                + '<div class="pl-act-label">' + c.label + '</div>'
                + '<div class="pl-act-value" style="color:' + c.color + '">' + c.value + '</div></div>';
        });
        el.innerHTML = html;
    }

    function renderIMsChart(data) {
        var months = data.items_by_month || {};
        if (!window.Chart || !Object.keys(months).length) {
            var el = document.getElementById('ma-ims-chart');
            if (el) el.innerHTML = '<div class="pl-empty">No chart data</div>';
            return;
        }
        var canvas = window.ensureCanvas('ma-ims-chart', 220);
        if (!canvas) return;

        var entries = Object.entries(months).sort();
        var labels = entries.map(function (e) {
            var m = parseInt(e[0].split('-')[1], 10) - 1;
            return (window.MONTH_SHORT || [])[m] || e[0];
        });
        var values = entries.map(function (e) { return e[1]; });

        var opts = window.chartOpts ? window.chartOpts(false) : {
            responsive: true, maintainAspectRatio: false,
            plugins: { legend: { display: false } }
        };
        var chart = new Chart(canvas, {
            type: 'bar',
            data: {
                labels: labels,
                datasets: [{
                    data: values,
                    backgroundColor: '#3CB4ADCC', hoverBackgroundColor: '#3CB4AD',
                    borderColor: '#3CB4AD', borderWidth: 1, borderRadius: 4, barPercentage: 0.7
                }]
            },
            options: opts
        });
        if (window.storeChart) window.storeChart('ma-ims-chart', chart);
    }

    function renderFlowStatusChart(data) {
        var counts = data.status_counts || {};
        if (!window.Chart || !Object.keys(counts).length) {
            var el = document.getElementById('ma-status-chart');
            if (el) el.innerHTML = '<div class="pl-empty">No status data</div>';
            return;
        }
        var canvas = window.ensureCanvas('ma-status-chart', 280);
        if (!canvas) return;

        var sorted = Object.entries(counts).sort(function (a, b) { return b[1] - a[1]; });
        var labels = sorted.map(function (e) { return e[0]; });
        var values = sorted.map(function (e) { return e[1]; });
        var colors = labels.map(function (l) { return STATUS_COLORS[l] || '#6b7280'; });

        var chart = new Chart(canvas, {
            type: 'bar',
            data: {
                labels: labels,
                datasets: [{
                    data: values,
                    backgroundColor: colors.map(function (c) { return c + 'CC'; }),
                    hoverBackgroundColor: colors,
                    borderColor: colors, borderWidth: 1, borderRadius: 4, barPercentage: 0.8
                }]
            },
            options: {
                indexAxis: 'y', responsive: true, maintainAspectRatio: false,
                plugins: {
                    legend: { display: false },
                    tooltip: {
                        backgroundColor: window.tipBg ? window.tipBg() : '#242833',
                        titleColor: '#fff', bodyColor: '#fff',
                        titleFont: { weight: '600' }, bodyFont: { size: 13 },
                        padding: 10, cornerRadius: 8
                    }
                },
                scales: {
                    x: {
                        beginAtZero: true,
                        grid: { color: window.gridCol ? window.gridCol() : 'rgba(0,0,0,0.06)' },
                        border: { display: false },
                        ticks: { font: { size: 11 }, color: window.tickCol ? window.tickCol() : '#94a3b8' }
                    },
                    y: {
                        grid: { display: false }, border: { display: false },
                        ticks: { font: { size: 11, weight: '600' }, color: window.tickCol ? window.tickCol() : '#94a3b8' }
                    }
                }
            }
        });
        if (window.storeChart) window.storeChart('ma-status-chart', chart);
    }

    function renderAllScores(projects) {
        var el = document.getElementById('ma-scores-bars');
        if (!el) return;

        var scored = projects
            .filter(function (p) {
                return (p.columns || {})['Latest IC Score (Avg.)'] && Number(p.columns['Latest IC Score (Avg.)']) > 0;
            })
            .map(function (p) {
                return { name: p.name, score: Number(p.columns['Latest IC Score (Avg.)']) };
            })
            .sort(function (a, b) { return b.score - a.score; });

        if (!scored.length) { el.innerHTML = '<div class="pl-empty">No scored deals</div>'; return; }

        var html = '';
        scored.forEach(function (item) {
            var pct = Math.min(100, Math.max(3, item.score));
            var c = item.score >= 70 ? '#34d399' : item.score >= 50 ? '#f59e0b' : '#ef4444';
            html += '<div class="stat-bar-item">'
                + '<div class="stat-bar-header">'
                + '<span class="stat-bar-label">' + esc(item.name) + '</span>'
                + '<span class="stat-bar-value" style="color:' + c + '">' + item.score + '%</span></div>'
                + '<div class="stat-bar-track">'
                + '<div class="stat-bar-fill" style="width:' + pct.toFixed(1) + '%;background:' + c
                + '"></div></div></div>';
        });
        el.innerHTML = html;
    }

    // ================================================================
    // TAB 3: Complete Scorecards
    // ================================================================
    function renderICKPIs(icItems) {
        var el = document.getElementById('ma-ic-kpis');
        if (!el) return;

        var scored = icItems.filter(function (i) {
            return i.scores && i.scores['Latest IC Score (Avg.)'] > 0;
        });
        var avg = scored.length
            ? (scored.reduce(function (s, i) { return s + i.scores['Latest IC Score (Avg.)']; }, 0) / scored.length).toFixed(0)
            : 0;
        var top = scored.length
            ? scored.sort(function (a, b) {
                return b.scores['Latest IC Score (Avg.)'] - a.scores['Latest IC Score (Avg.)'];
            })[0] : null;

        var cards = [
            { label: 'Scored Items', value: scored.length, color: '#334FB4' },
            { label: 'Avg IC Score', value: avg + '%', color: '#3CB4AD' },
            { label: 'Highest Score', value: top ? top.scores['Latest IC Score (Avg.)'] + '%' : '0%',
              color: '#34d399', sub: top ? top.name : '' }
        ];

        var html = '';
        cards.forEach(function (c) {
            html += '<div class="pl-act-card">'
                + '<div class="pl-act-label">' + c.label + '</div>'
                + '<div class="pl-act-value" style="color:' + c.color + '">' + c.value + '</div>'
                + (c.sub ? '<span class="text-muted-sm">' + esc(c.sub) + '</span>' : '')
                + '</div>';
        });
        el.innerHTML = html;
    }

    function renderScorecardTable(projects) {
        var el = document.getElementById('ma-ic-table');
        if (!el) return;

        var withScores = projects.filter(function (p) {
            if (DEAD_GROUPS.indexOf(p.group) !== -1) return false;
            var c = p.columns || {};
            return c['Latest IC Score (Avg.)'] || c['Gate 0 Score'] || c['Gate 1 Score'];
        });

        if (!withScores.length) {
            el.innerHTML = '<div class="pl-empty">No scorecard data</div>';
            return;
        }

        var groups = {};
        STAGE_ORDER.forEach(function (s) { groups[s] = []; });
        withScores.forEach(function (p) { if (groups[p.group]) groups[p.group].push(p); });

        var html = '';
        STAGE_ORDER.forEach(function (stage) {
            var items = groups[stage];
            if (!items || !items.length) return;
            var sc = STAGE_COLORS[stage] || '#6b7280';

            html += '<div style="margin-bottom:16px">'
                + '<div style="display:flex;align-items:center;gap:8px;padding:8px 12px;background:'
                + sc + '18;border-left:3px solid ' + sc + ';border-radius:6px;margin-bottom:6px">'
                + '<span style="font-weight:700;font-size:13px;color:' + sc + '">' + esc(stage) + '</span>'
                + '<span style="font-size:11px;color:var(--text-muted)">' + items.length + ' deals</span></div>';

            html += '<div style="overflow-x:auto"><table class="pl-deals-table"><thead><tr>'
                + '<th>Deal</th><th>POC</th><th>Status</th><th>Priority</th>'
                + '<th>Deal Type</th><th>Deal Source</th><th>Valuation</th><th>Target %</th>'
                + '<th>Gate 0</th><th>Gate 1</th><th>Gate 2</th><th>Gate 3</th>'
                + '<th>IC Avg</th><th>CDD</th></tr></thead><tbody>';

            items.sort(function (a, b) {
                return Number((b.columns || {})['Latest IC Score (Avg.)'] || 0)
                     - Number((a.columns || {})['Latest IC Score (Avg.)'] || 0);
            });

            items.forEach(function (p) {
                var c = p.columns || {};
                var subs = p.subitems || [];
                var done = subs.filter(function (s) { return s.done; }).length;
                var total = subs.length || p.subitems_count || 0;
                var cdd = total > 0 ? (subs.length ? done : p.subitems_complete) + '/' + total : '-';

                html += '<tr>'
                    + '<td class="pl-deal-name">' + esc(p.name) + '</td>'
                    + '<td class="text-muted-sm">' + esc(c['POC'] || '-') + '</td>'
                    + '<td>' + chip(p.status) + '</td>'
                    + '<td>' + chip(c['Priority'] || '-', PRIORITY_COLORS[c['Priority']]) + '</td>'
                    + '<td class="text-muted-sm">' + esc(c['Deal Type'] || '-') + '</td>'
                    + '<td class="text-muted-sm">' + esc(c['Deal Source'] || '-') + '</td>'
                    + '<td style="font-weight:600">' + (c['Valuation'] ? fmtK(c['Valuation']) : '-') + '</td>'
                    + '<td>' + (c['Target Equity Purchase'] ? c['Target Equity Purchase'] + '%' : '-') + '</td>'
                    + scoreCell(c['Gate 0 Score'], 'Gate 0')
                    + scoreCell(c['Gate 1 Score'], 'Gate 1')
                    + scoreCell(c['Gate 2 Score'], 'Gate 2')
                    + scoreCell(c['Gate 3 Score'], 'Gate 3')
                    + scoreCell(c['Latest IC Score (Avg.)'], 'IC Average')
                    + '<td class="text-muted-sm">' + cdd + '</td></tr>';
            });
            html += '</tbody></table></div></div>';
        });

        el.innerHTML = html || '<div class="pl-empty">No scorecard data</div>';
    }

    function renderICDistribution(icItems) {
        var el = document.getElementById('ma-ic-dist');
        if (!el) return;

        var buckets = [
            { label: '80\u2013100%', min: 80, max: 101, count: 0 },
            { label: '70\u201379%', min: 70, max: 80, count: 0 },
            { label: '50\u201369%', min: 50, max: 70, count: 0 },
            { label: '30\u201349%', min: 30, max: 50, count: 0 },
            { label: '1\u201329%', min: 1, max: 30, count: 0 }
        ];
        icItems.forEach(function (item) {
            var s = item.scores ? (item.scores['Latest IC Score (Avg.)'] || 0) : 0;
            for (var i = 0; i < buckets.length; i++) {
                if (s >= buckets[i].min && s < buckets[i].max) { buckets[i].count++; break; }
            }
        });

        var mx = Math.max.apply(null, buckets.map(function (b) { return b.count; })) || 1;
        var colors = ['#34d399', '#3CB4AD', '#334FB4', '#f59e0b', '#ef4444'];
        var html = '';
        buckets.forEach(function (b, i) {
            var pct = Math.max(3, (b.count / mx) * 100);
            html += '<div class="stat-bar-item"><div class="stat-bar-header">'
                + '<span class="stat-bar-label">' + b.label + '</span>'
                + '<span class="stat-bar-value">' + b.count + ' deals</span></div>'
                + '<div class="stat-bar-track"><div class="stat-bar-fill" style="width:' + pct.toFixed(1)
                + '%;background:' + colors[i] + '"></div></div></div>';
        });
        el.innerHTML = html;
    }

    function renderCDDProgress(projects) {
        var el = document.getElementById('ma-cdd-progress');
        if (!el) return;

        var withSubs = projects.filter(function (p) {
            if (DEAD_GROUPS.indexOf(p.group) !== -1) return false;
            return (p.subitems && p.subitems.length > 0) || p.subitems_count > 0;
        }).sort(function (a, b) {
            var pA = a.subitems_count > 0 ? a.subitems_complete / a.subitems_count : 0;
            var pB = b.subitems_count > 0 ? b.subitems_complete / b.subitems_count : 0;
            return pB - pA;
        });

        if (!withSubs.length) { el.innerHTML = '<div class="pl-empty">No CDD data</div>'; return; }

        var html = '';
        withSubs.forEach(function (p) {
            var subs = p.subitems || [];
            var total = subs.length || p.subitems_count || 0;
            var done = subs.length ? subs.filter(function (s) { return s.done; }).length : (p.subitems_complete || 0);
            var pct = total > 0 ? Math.round((done / total) * 100) : 0;
            var c = pct === 100 ? '#34d399' : pct >= 50 ? '#f59e0b' : '#ef4444';

            html += '<div style="margin-bottom:10px">'
                + '<div style="display:flex;justify-content:space-between;margin-bottom:4px;font-size:12px">'
                + '<span style="color:var(--text);font-weight:600">' + esc(p.name) + '</span>'
                + '<span style="color:' + c + ';font-weight:700">' + done + '/' + total
                + ' (' + pct + '%)</span></div>'
                + '<div style="height:6px;background:var(--card-border);border-radius:3px;overflow:hidden">'
                + '<div style="height:100%;width:' + pct + '%;background:' + c
                + ';border-radius:3px;transition:width .6s cubic-bezier(.25,.1,.25,1)"></div></div>';

            if (subs.length) {
                html += '<div style="display:flex;gap:4px;margin-top:4px;flex-wrap:wrap">';
                subs.forEach(function (s) {
                    var sc = s.done ? '#34d399' : '#6b7280';
                    html += '<span style="font-size:10px;padding:2px 6px;border-radius:4px;background:'
                        + sc + '20;color:' + sc + '">' + (s.done ? '\u2713 ' : '') + esc(s.name) + '</span>';
                });
                html += '</div>';
            }
            html += '</div>';
        });
        el.innerHTML = html;
    }

    // ================================================================
    // New Opportunity — modal + Monday.com creation
    // ================================================================
    function openNewOppModal() {
        var modal = document.getElementById('ma-new-opp-modal');
        if (modal) modal.classList.remove('hidden');
    }
    function closeNewOppModal() {
        var modal = document.getElementById('ma-new-opp-modal');
        if (modal) modal.classList.add('hidden');
    }

    // Wire button (may load before or after page fragment)
    document.addEventListener('click', function (e) {
        if (e.target.closest('#ma-new-opp-btn')) openNewOppModal();
    });

    // Form submit — create item + subitems in Monday.com
    document.addEventListener('submit', function (e) {
        if (e.target.id !== 'ma-new-opp-form') return;
        e.preventDefault();

        var name = document.getElementById('ma-opp-name').value.trim();
        if (!name) return;

        var source = document.getElementById('ma-opp-source').value;
        var dealType = document.getElementById('ma-opp-type').value;
        var priority = document.getElementById('ma-opp-priority').value;

        var btn = e.target.querySelector('[type="submit"]');
        if (btn) { btn.disabled = true; btn.textContent = 'Creating\u2026'; }

        var colVals = JSON.stringify({
            status: { label: 'Pending Info' },
            color_mkvyy4xx: { label: priority },
            color_mkwfgbfw: { label: dealType },
            color_mkzw1d8h: { label: source }
        });

        var createQuery = 'mutation { create_item(board_id: 1674745475, group_id: "group_mksmm6p5", item_name: "' + name.replace(/"/g, '\\"') + '", column_values: "' + colVals.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '") { id } }';

        fetch('/api/skill-execute', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ _type: 'api-call', target: 'monday', query: createQuery })
        })
        .then(function (r) { return r.json(); })
        .then(function (data) {
            if (data.error) throw new Error(data.error);
            var itemId = data.data && data.data.create_item && data.data.create_item.id;
            if (!itemId) throw new Error('No item ID returned');

            // Create 5 CDD subitems
            var subs = ['IM & KPIs', 'Gate 0 Scorecard', 'Gate 0 One-pager', 'Gate 1 CDD', 'Gate 2 Final Review'];
            return Promise.all(subs.map(function (sub) {
                var subQuery = 'mutation { create_subitem(parent_item_id: ' + itemId + ', item_name: "' + sub + '", board_id: 1674745475) { id } }';
                return fetch('/api/skill-execute', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ _type: 'api-call', target: 'monday', query: subQuery })
                });
            }));
        })
        .then(function () {
            if (window.Toast) window.Toast.success('Opportunity "' + name + '" created in Monday.com with 5 CDD subitems');
            closeNewOppModal();
            e.target.reset();
        })
        .catch(function (err) {
            console.error('Create opportunity failed:', err);
            if (window.Toast) window.Toast.error('Failed to create opportunity: ' + err.message);
        })
        .finally(function () {
            if (btn) { btn.disabled = false; btn.textContent = 'Create in Monday.com'; }
        });
    });

    // ================================================================
    // Master render
    // ================================================================
    window.renderMAHub = function () {
        var data = window.MONDAY;
        if (!data || !data.projects) {
            var el = document.getElementById('ma-main-table');
            if (el) el.innerHTML = '<div class="pl-empty">No Monday.com data loaded. Run generate_monday_dashboard.py to sync.</div>';
            return;
        }

        renderMainTable(data.projects);
        renderPerfKPIs(data.projects);
        renderIMsChart(data);
        renderFlowStatusChart(data);
        renderAllScores(data.projects);
        renderICKPIs(data.ic_items || []);
        renderScorecardTable(data.projects);
        renderICDistribution(data.ic_items || []);
        renderCDDProgress(data.projects);
    };
})();
